version: "3"

services:
  app:
    build: .
    environment:
      GIN_MODE: "release"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8081:8081"
    command: go run main.go
    links:
      - database

  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: fuFUn6S3NENFSAx5
      POSTGRES_USER: mailer
      POSTGRES_DB: gomail
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: V794QYkkpLUW8NfpW7wtZRnJRLnKVy
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbitmq
