version: "3"

services:
  app:
    build: .
    environment:
      GIN_MODE: "release"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8081:8081"
    command: go run main.go
    links:
      - database
      - fake-smtp

  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  fake-smtp:
    image: munkyboy/fakesmtp
    container_name: fake-smtp
    ports:
      - "25:25"
    volumes:
      - ./fake-smtp-emails:/var/mail
